### ISSUE TITLE
Unnecessary "Invoking a constructor without parens and without arguments" error

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#421] opened 2015-05-16 11:37 UTC
With `empty_constructor_needs_parens` enabled, for the following line:

```coffee
new OPERATIONS[operationSpec.type] operationSpec.field
```

I am getting this error:

```
Invoking a constructor without parens and without arguments.
```

This seems erroneous.

**Comment by AsaAyers** [comment] 2015-05-16 11:57
I thought I recognized you :)

I was thinking this was a duplicate of #308, but I see the issue here is that you _are_ passing arguments. CoffeeLint just isn't recognizing those arguments.

**Comment by mitar** [comment] 2015-05-16 12:01
Oh, I also had some memories I was reporting this already. :-)

**Comment by AsaAyers** [comment] 2015-05-16 15:12
I went back and read that other issue again. It is actually the same. This morning when I read it I was thinking the other issue was about `camel_case_classes` and maybe CoffeeLint complains about `new foo()` vs `new Foo()`

**Closed** 2015-05-16 15:12 UTC
Labels: bug

**Comment by mitar** [comment] 2015-05-16 20:08
Oh, true.
