### ISSUE TITLE
Invalid "Wrong count of newlines between a class and other code"

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#423] opened 2015-05-16 11:40 UTC
For the following file:

```coffee
if true
  class Test

  foo = ->
    true

  bar = ->
    true
```

There is the following error:

```
#7: Wrong count of newlines between a class and other code. Expected 1 got 2.
```

With:

```json
    "newlines_after_classes": {
        "value": 1,
        "level": "error"
    },
```

This seems erroneous.

**Comment by AsaAyers** [comment] 2015-05-16 12:01
I'm going to close this as a duplicate of #375. I think that has been one of the most problematic rules we have.

**Closed by AsaAyers** 2015-05-16 12:01 UTC
