### ISSUE TITLE
Indentation with Tabs

### ISSUE THREAD

**Issue by niclashoyer** [clutchski/coffeelint#135] opened 2013-07-08 13:56 UTC
I'm following the `tabs for indentation, spaces for alignment` rule in my project. I don't want to bring up the tabs vs. spaces discussion here. It would be nice if I could forbid spaces instead of tabs e.g. something similar to `no_tabs` like `no_spaces`.

**Comment by AsaAyers** [comment] 2015-05-19 13:34
After more than a year of not having any feedback on how this should work I'm just going to close it.

**Closed by AsaAyers** 2015-05-19 13:34 UTC

**Comment by azizhk** [comment] 2015-07-24 13:49
Hi @AsaAyers,
Please reopen this issue.

For your question: If you want to forbid spaces how do you expect spaces for alignment to work?
How about for tabs in the beginning of the line, we allow it.
No indentation before any non whitespace characters, but they should be used to allow aligning object declaration.
How does that sound?

**Comment by AsaAyers** [comment] 2015-07-24 13:58
Based on what I've seen here you're the only person who has been interested in this for nearly 2 years. If you want to open a PR for this I'll review it, but I don't see any reason to re-open this. I'm certainly not going to implement this change myself.

**Comment by staticshock** [comment] 2015-07-24 14:08
If you're looking for "activity", I'll chime in. I would use the `no_spaces` flag if it was available.

**Comment by AsaAyers** [comment] 2015-07-24 14:37
More important than activity is someone who is going to do the work. It only makes sense to re-open this if no one subscribed will do the work and we believe that if the issue is re-opened it will draw the attention of someone else who wants to do this. Given that this is 2 years old and was open for more than a year with no activity at all I just don't think it's going to attract someone who wants to work on this.

**Comment by azizhk** [comment] 2015-07-24 21:16
Hi,
I completely agree with your thinking, it makes no sense to support feature requests when there is very little popularity :stuck_out_tongue_winking_eye:

I've tried a sort of hack for it. https://github.com/azizhk/coffeelint/pull/1
Would love if you could review it.
I have not followed the `no_spaces` flag as it would sound ambiguous, so just modified the indentation module to support a `use: 'tabs'` option.

I've not created a pull request into your repo as I still have to add test cases, then squash them down to one commit etc.

**Comment by laurentpayot** [comment] 2015-08-03 16:37
+1 for <code>use: 'tabs'</code>
